<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nh_fluid_pdf_view"
 *
 * Auto generated by Extension Builder 2013-12-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Fluid PDF view',
	'description' => '',
	'category' => 'misc',
	'author' => 'Nikolas Hagelstein',
	'author_email' => 'nikolas.hagelstein@gmail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'webkitpdf' => '1.2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>